# Elevator System 1: interactive control-logic simulation.
# No physical plant is attached; Current_Floor is generated by the YAML model.

import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
EXAMPLE_DIR = THIS_DIR.parent
REPO_ROOT = EXAMPLE_DIR.parent
ENGINE_DIR = REPO_ROOT / "engine"

sys.path.insert(0, str(ENGINE_DIR))
sys.path.insert(0, str(EXAMPLE_DIR))

from simulation_runner import setup_simulation
from elevator_viz import run_interactive


def find_yaml(folder):
    """Return the single YAML system description in this example folder."""
    candidates = list(folder.glob("*.yaml")) + list(folder.glob("*.yml"))

    if len(candidates) != 1:
        raise FileNotFoundError(
            f"Expected exactly one YAML file in {folder}, "
            f"found {len(candidates)}: {candidates}"
        )

    return candidates[0]


YAML_PATH = find_yaml(THIS_DIR)


if __name__ == "__main__":
    operations, fb_instances, tags = setup_simulation(
        str(YAML_PATH),
        scan_time=1,
    )

    run_interactive(
        operations,
        fb_instances,
        tags,
        top_floor=tags["Top_Floor"],
        plant=None,
        title="Elevator_System_1 -- click a floor to call the car",
    )